github:
  description: "Apache OpenWhisk is an open source serverless cloud platform"
  homepage: https://openwhisk.apache.org/
  labels:
    - openwhisk
    - apache
    - serverless
    - faas
    - functions-as-a-service
    - cloud
    - serverless-architectures
    - serverless-functions
    - docker
    - kubernetes
    - functions
  protected_branches:
    master:
      required_status_checks:
        strict: true
        contexts:
          - "Travis CI - Pull Request"
      required_pull_request_reviews:
        required_appoving_review_count: 1
      required_signatures: false
  enabled_merge_buttons:
    merge: false
    squash: true
    rebase: true
  features:
    issues: true

notifications:
  commits: dmytro.solovei@motorolasolutions.com
  issues_status: dmytro.solovei@motorolasolutions.com
  issues_comment: dmytro.solovei@motorolasolutions.com
  pullrequests_status: dmytro.solovei@motorolasolutions.com
  pullrequests_comment: dmytro.solovei@motorolasolutions.com
