name: Build and publish deployer

on:
  workflow_dispatch:
    inputs:
      forcePublish:
        description: Force Docker/package push even on a non-main branch
        type: boolean
        required: false
        default: 'false'
  push:
    branches: [ 'main' ]
    paths:
      - 'deployer/**'
      - '.github/workflows/build-and-publish-deployer.yml'
  pull_request:
    branches: [ '*' ]
    paths:
      - 'deployer/**'
      - '.github/workflows/build-and-publish-deployer.yml'

defaults:
  run:
    shell: bash

jobs:
  build:
    env:
      ORG_GRADLE_PROJECT_githubArtifactsToken: ${{ secrets.GITHUB_TOKEN }}
      ORG_GRADLE_PROJECT_azureArtifactsToken: ${{ secrets.AZURE_ARTIFACTS_TOKEN }}
    name: Build and publish deployer
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Build deployer
        run: ./gradlew :deployer:build
        working-directory: ./
        
        - name: Branch protection ON
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/:repository/branches/master/protection
          repository: ${{ github.repository }}
          mediaType: |
            previews: 
              - luke-cage
          required_status_checks: |
            strict: true
            contexts:
              - build

      - name: Publish deployer
        if: github.ref == 'refs/heads/main' || github.event.inputs.forcePublish == 'true'
        run: ./gradlew :deployer:publish
        working-directory: ./
